### ISSUE TITLE
Validator, sorting and locale

### ISSUE THREAD

**Issue by TomazErjavec** [UniversalDependencies/tools#4] opened 2015-05-15 17:18 UTC
I don't know Python, so not sure how sort works there, but in Perl - which I used to produce the treebank - it is dependent on the locale settings. And, although I sorted my features, the validator complained that they were unsorted, because of "|NumType=Card|Number=Plur".
It seems that Slovene locale puts capital letters before lower case ones.
Not sure if this is an issue of simply documenting the validator (e.g. "should be sorted according to C locale") or if this impacts the code.

**Comment by fginter** [comment] 2015-05-15 17:47
Hi. This is not locale, but a requirement in the conllu standard here: http://universaldependencies.github.io/docs/format.html It says " In sorting, uppercase letters are considered identical to their lowercase counterparts" and the validator implements this. So Number should indeed come before NumType. I.e. not a bug. Closing.

**Closed by fginter** 2015-05-15 17:47 UTC
Labels: enhancement

**Comment by TomazErjavec** [comment] 2015-05-15 20:48
You are right in the above - so C locale should be ok. But then the problem was in square brackets:
|Gender=Fem|Gender[psor]=Fem|
I now see that the specs do say "Both feature names and values must have the form [A-Z0-9][a-zA-Z0-9]*." but we took the above features from Czech, and Czech passes validation.
So, you do have a bug :)

**Comment by fginter** [comment] 2015-05-15 21:12
1) At least on my machine `Gender=Fem|Gender[psor]=Fem` validates and `Gender[psor]=Fem|Gender=Fem` does not validate. That is precisely as it should be (features are in alphabetic order ie Gender comes before Gender[psor]). Are you saying that for you the validator reports the opposite?

2) OK yes we should fix the description to allow for Gender[psor]. The validator implements this though.

**Comment by fginter** [comment] 2015-05-15 21:19
BTW: The square brackets are the layered features described at the bottom of http://universaldependencies.github.io/docs/u/overview/morphology.html The only discrepancy I can see is that their existence is not mentioned in the CoNLL-U format description. The validator does allow them as it should.

**Comment by TomazErjavec** [comment] 2015-05-16 12:08
> At least on my machine Gender=Fem|Gender[psor]=Fem validates
Sorry, it was late at night and I misread the reason for failure, this is the complete line:
$ python tools/validate.py --noecho --lang=sl UD_Slovenian/sl-ud-dev.conllu
[Line         41]: Morphological features must be sorted: 'Case=Acc|Gender=Fem|Gender[psor]=Fem|Number[psor]=Sing|Number=Sing|Person=3|PronType=Prs'
So, Gender is ok, but Number isn't. I have to check what is happening with the Perl sort, as it seems to once put the = before the [, and the second time in the inverse order. Very strange...

> The only discrepancy I can see is that their existence is not mentioned in the CoNLL-U format  description
Yes, that was my point: the validator should implement the format description, i.e. the format description should be extended to allow [] (which is, admittedly, a pain, as you have to escape them in the set..)

Thanks for your help!
